#!/usr/bin/env python3
"""
生成修改前缀后的 comexport.def 文件

用法：
    python generate_new_def.py [NEW_PREFIX]
    
示例：
    python generate_new_def.py MYPREFIX
    python generate_new_def.py RDX
"""

import sys
import os

# 所有需要导出的 RENDERDOC_ 函数（从实际导出表提取）
RENDERDOC_FUNCTIONS = [
    "RENDERDOC_AllocArrayMem",
    "RENDERDOC_BecomeRemoteServer",
    "RENDERDOC_BeginProfileRegion",
    "RENDERDOC_CanGlobalHook",
    "RENDERDOC_CanSelfHostedCapture",
    "RENDERDOC_CheckAndroidPackage",
    "RENDERDOC_CheckRemoteServerConnection",
    "RENDERDOC_CreateBugReport",
    "RENDERDOC_CreateRemoteServerConnection",
    "RENDERDOC_CreateTargetControl",
    "RENDERDOC_EndProfileRegion",
    "RENDERDOC_EndSelfHostCapture",
    "RENDERDOC_EnumerateRemoteTargets",
    "RENDERDOC_ExecuteAndInject",
    "RENDERDOC_FloatToHalf",
    "RENDERDOC_FreeArrayMem",
    "RENDERDOC_GetAPI",
    "RENDERDOC_GetCommitHash",
    "RENDERDOC_GetConfigSetting",
    "RENDERDOC_GetCurrentProcessMemoryUsage",
    "RENDERDOC_GetDefaultCaptureOptions",
    "RENDERDOC_GetDeviceProtocolController",
    "RENDERDOC_GetDriverInformation",
    "RENDERDOC_GetLogFile",
    "RENDERDOC_GetLogFileContents",
    "RENDERDOC_GetSupportedDeviceProtocols",
    "RENDERDOC_GetVersionString",
    "RENDERDOC_HalfToFloat",
    "RENDERDOC_InitCamera",
    "RENDERDOC_InitialiseReplay",
    "RENDERDOC_InjectIntoProcess",
    "RENDERDOC_IsGlobalHookActive",
    "RENDERDOC_IsReleaseBuild",
    "RENDERDOC_LogMessage",
    "RENDERDOC_NeedVulkanLayerRegistration",
    "RENDERDOC_NumVerticesPerPrimitive",
    "RENDERDOC_OpenCaptureFile",
    "RENDERDOC_RegisterMemoryRegion",
    "RENDERDOC_ResourceFormatName",
    "RENDERDOC_RunFunctionalTests",
    "RENDERDOC_RunUnitTests",
    "RENDERDOC_SaveConfigSettings",
    "RENDERDOC_SetColors",
    "RENDERDOC_SetConfigSetting",
    "RENDERDOC_SetDebugLogFile",
    "RENDERDOC_ShutdownReplay",
    "RENDERDOC_StartGlobalHook",
    "RENDERDOC_StartSelfHostCapture",
    "RENDERDOC_StopGlobalHook",
    "RENDERDOC_UnregisterMemoryRegion",
    "RENDERDOC_UpdateInstalledVersionNumber",
    "RENDERDOC_UpdateVulkanLayerRegistration",
    "RENDERDOC_VertexOffset",
]

# INTERNAL_ 函数（通常不需要改，但如果要完全控制导出表，也需要处理）
INTERNAL_FUNCTIONS = [
    "INTERNAL_ApplyEnvMods",
    "INTERNAL_EnvMod",
    "INTERNAL_EnvModName",
    "INTERNAL_EnvModValue",
    "INTERNAL_EnvSep",
    "INTERNAL_GetTargetControlIdent",
    "INTERNAL_SetCaptureFile",
    "INTERNAL_SetCaptureOptions",
    "INTERNAL_SetDebugLogFile",
]

# VK_LAYER 函数（Vulkan 层函数，通常保持原样）
VK_LAYER_FUNCTIONS = [
    "VK_LAYER_RENDERDOC_CaptureEnumerateDeviceExtensionProperties",
    "VK_LAYER_RENDERDOC_CaptureEnumerateDeviceLayerProperties",
    "VK_LAYER_RENDERDOC_CaptureEnumerateInstanceExtensionProperties",
    "VK_LAYER_RENDERDOC_CaptureGetDeviceProcAddr",
    "VK_LAYER_RENDERDOC_CaptureGetInstanceProcAddr",
    "VK_LAYER_RENDERDOC_CaptureNegotiateLoaderLayerInterfaceVersion",
    "VK_LAYER_RENDERDOC_Capture_layerGetPhysicalDeviceProcAddr",
]


def generate_def_file_alias(new_prefix="MYPREFIX"):
    """
    生成方式 1：添加别名（原名保留）
    
    优点：不需要修改源代码
    缺点：导出表会同时包含两套名字
    """
    content = [
        "; Auto-generated by generate_new_def.py",
        "; 方式 1：添加别名（原名 RENDERDOC_* 仍然保留）",
        "",
        "EXPORTS",
        "   DllGetClassObject PRIVATE",
        "   DllCanUnloadNow PRIVATE",
        "",
        "   ; RENDERDOC_* 公共 API 函数别名",
    ]
    
    for func in sorted(RENDERDOC_FUNCTIONS):
        new_name = func.replace("RENDERDOC_", f"{new_prefix}_")
        content.append(f"   {new_name} = {func}")
    
    return "\n".join(content)


def generate_def_file_exclusive(new_prefix="MYPREFIX"):
    """
    生成方式 2：只导出新名字（需要修改源代码移除 __declspec(dllexport)）
    
    优点：导出表干净，只有新前缀
    缺点：需要修改 apidefs.h 和 win32_process.cpp
    """
    content = [
        "; Auto-generated by generate_new_def.py",
        "; 方式 2：只导出新名字（需要先移除源代码中的 __declspec(dllexport)）",
        "; ",
        "; 步骤：",
        "; 1. 修改 renderdoc/api/replay/apidefs.h:",
        ";    #define RENDERDOC_EXPORT_API  // 留空",
        "; ",
        "; 2. 修改 renderdoc/os/win32/win32_process.cpp:",
        ";    移除所有 __declspec(dllexport)",
        "; ",
        "; 3. 使用此 .def 文件替换 os/win32/comexport.def",
        "",
        "EXPORTS",
        "   DllGetClassObject PRIVATE",
        "   DllCanUnloadNow PRIVATE",
        "",
        "   ; RENDERDOC_* 公共 API 函数（使用新前缀）",
    ]
    
    for func in sorted(RENDERDOC_FUNCTIONS):
        new_name = func.replace("RENDERDOC_", f"{new_prefix}_")
        content.append(f"   {new_name} = {func}")
    
    content.extend([
        "",
        "   ; INTERNAL_* 内部函数（保持原名）",
    ])
    
    for func in sorted(INTERNAL_FUNCTIONS):
        content.append(f"   {func} = {func}")
    
    content.extend([
        "",
        "   ; VK_LAYER_RENDERDOC_* Vulkan 层函数（保持原名）",
    ])
    
    for func in sorted(VK_LAYER_FUNCTIONS):
        content.append(f"   {func} = {func}")
    
    return "\n".join(content)


def main():
    new_prefix = "MYPREFIX"
    
    if len(sys.argv) > 1:
        new_prefix = sys.argv[1].upper().rstrip("_")
    
    print(f"生成新的 .def 文件，使用前缀: {new_prefix}_")
    print()
    
    # 生成方式 1：添加别名
    alias_content = generate_def_file_alias(new_prefix)
    alias_file = f"comexport_alias_{new_prefix.lower()}.def"
    
    with open(alias_file, "w", encoding="utf-8") as f:
        f.write(alias_content)
    
    print(f"✓ 已生成：{alias_file}")
    print(f"  方式 1：添加别名（不需要修改源代码）")
    print(f"  导出表将同时包含 RENDERDOC_* 和 {new_prefix}_*")
    print()
    
    # 生成方式 2：只导出新名字
    exclusive_content = generate_def_file_exclusive(new_prefix)
    exclusive_file = f"comexport_exclusive_{new_prefix.lower()}.def"
    
    with open(exclusive_file, "w", encoding="utf-8") as f:
        f.write(exclusive_content)
    
    print(f"✓ 已生成：{exclusive_file}")
    print(f"  方式 2：只导出新名字（需要修改源代码）")
    print(f"  导出表只包含 {new_prefix}_*")
    print()
    
    print("使用说明：")
    print("=" * 60)
    print("方式 1（简单，但有两套名字）：")
    print(f"  1. 复制 {alias_file} 到 renderdoc/os/win32/comexport.def")
    print("  2. 重新编译项目")
    print("  3. 测试导出表：dumpbin /EXPORTS renderdoc.dll")
    print()
    print("方式 2（干净，但需要改源码）：")
    print("  1. 修改 renderdoc/api/replay/apidefs.h (80 行)：")
    print("     #define RENDERDOC_EXPORT_API  // 留空")
    print("  2. 修改 renderdoc/os/win32/win32_process.cpp：")
    print("     移除所有 __declspec(dllexport)")
    print(f"  3. 复制 {exclusive_file} 到 renderdoc/os/win32/comexport.def")
    print("  4. 重新编译项目")
    print("  5. 测试导出表：dumpbin /EXPORTS renderdoc.dll")
    

if __name__ == "__main__":
    main()

